### ISSUE TITLE
Line: 56, Exit Code: 35

### ISSUE THREAD

**Issue by Wolfstar258** [RiiConnect24/RiiConnect24-Patcher#169] opened 2023-12-28 20:13 UTC
I tried to run the patcher on my Mac (running Catalina), but this error shows up everytime. Permission for Terminal to access Desktop and Downloads files is enabled, so I’m not sure what’s going on.

![image](https://github.com/RiiConnect24/RiiConnect24-Patcher/assets/116023966/639726e4-4555-4781-a28f-7b5d99dd5000)

**Comment by TheShadowEevee** [comment] 2023-12-28 21:33
If you would like to ask if there's been any updates or if you have more information you would like to provide, it is best to do that in the original issue instead of opening a new one.

Duplicate of #164, locking this issue in favor of further discussion in the original issue.

**Closed by TheShadowEevee** 2023-12-28 21:33 UTC
