### ISSUE TITLE
How can I patch Dolphin under Linux?

### ISSUE THREAD

**Issue by AnErrupTion** [RiiConnect24/RiiConnect24-Patcher#82] opened 2021-06-20 08:46 UTC
In the current latest RiiConnect24 patcher, there's no option (at least on the Unix patcher) to patch Dolphin, only the Wii and vWii.
How can I patch Dolphin under Linux then? Is it still experimental?

![image](https://user-images.githubusercontent.com/49339966/122667738-ef52fd80-d1a3-11eb-9328-4c753da7fa5f.png)

**Comment by KcrPL** [comment] 2021-06-20 08:48
This feature is unavailable on the Unix version of the patcher. For now, you can only do that on Windows.

Not an issue, closing unless @SketchMaster2001 wants to open it.

**Comment by SketchMaster2001** [comment] 2021-06-21 12:56
On the main menu, you can choose to open the .VFF Downloader, which will assist you in patching Dolphin.

**Comment by AnErrupTion** [comment] 2021-06-21 15:46
When I choosed the channels to add, it returned me to the main menu, and in Dolphin I don't see any channels, nor do I see in the Wii NAND folder any WAD files.

**Comment by SketchMaster2001** [comment] 2021-06-30 15:41
I don't know why I reopened this as it is not a bug, closing.

**Comment by SketchMaster2001** [comment] 2021-06-30 15:41
> When I choosed the channels to add, it returned me to the main menu, and in Dolphin I don't see any channels, nor do I see in the Wii NAND folder any WAD files.

Regarding this, you probably do not have the Wii Menu installed on Dolphin. You must get a Wii Menu WAD. I cannot tell you where to get one so please do not ask.

**Closed by SketchMaster2001** 2021-06-30 15:41 UTC
Labels: Unix
