### ISSUE TITLE
Patcher crashes after selecting start

### ISSUE THREAD

**Issue by Siriusdish** [RiiConnect24/RiiConnect24-Patcher#55] opened 2020-12-03 17:46 UTC
I run the patcher and select the start option and it looks for updates and crashes immediately.

**Comment by KcrPL** [comment] 2020-12-03 18:39
What OS are you on? And do you know how to use CMD,exe?

**Comment by longboarder241** [comment] 2020-12-28 04:00
Mine is doing the same thing. I tried it on my 32 bit computer as it has less issues but it crashes too. Since it doesn't close as fast I was able to see a message saying checking for updates. For information I'm doing this on windows 10 and I have the proper .net framework installed

**Comment by KcrPL** [comment] 2020-12-28 08:51
Did this happen on the latest update?

**Comment by Soan7** [comment] 2021-01-07 17:01
yes

**Comment by alistair1980** [comment] 2021-02-02 21:10
Having the same issue open the batch file, and as soon as i put in 1 and Enter it crashes.. Using windows 10 English

**Comment by Siriusdish** [comment] 2021-03-14 22:05
> 
> 
> What OS are you on? And do you know how to use CMD,exe?

Im on windows 10 64 bit and I don't know how to use CMD.exe

**Comment by Siriusdish** [comment] 2021-03-14 22:12
also I tried the wiimmfi patcher and that crashes too

**Comment by TheShadowEevee** [comment] 2021-03-14 22:18
Interesting, @Siriusdish can you try something?

1. Re-Download the latest version of the patcher (Delete any old ones first)
2. Press Win+X and select "Windows Powershell"
3. Type in the command `cd ~/Downloads`
4. Type `./RiiConnect24Patcher.bat`
5. Try to use the patcher, it should be running in the powershell window.

It will likely still crash, but it might be able to show more information.
If it does crash again, it would also be helpful if you ran `$LastExitCode` as a command as well, and send the output of both the patcher and that command.

**Comment by Siriusdish** [comment] 2021-03-15 00:50
![image](https://user-images.githubusercontent.com/75284268/111090629-aa0c9900-84ed-11eb-95bf-bd61ad462905.jpeg) this is what shows after I type 1 then enter

**Comment by Siriusdish** [comment] 2021-03-15 00:50
And when I ran $lastexitcode it said 1

**Comment by TheShadowEevee** [comment] 2021-03-15 00:57
Thanks! I just tested, I can confirm that the patcher crashes when it can't detect an internet connection. 

I will create a commit to fix this, and I'll comment once I've done that. In the mean time, you should check your internet connection. Are you using a proxy or a VPN or anything?

**Comment by TheShadowEevee** [comment] 2021-03-15 01:00
You can download the fix [here](https://raw.githubusercontent.com/RiiConnect24/RiiConnect24-Patcher/master/RiiConnect24Patcher.bat), let me know if it works.

If it shows a bunch of text in your web browser Right Click it and select "Save As..."

**Comment by IsTheWit** [comment] 2021-03-25 15:45
same thing, but on mac

**Comment by TheShadowEevee** [comment] 2021-03-25 16:01
@IsTheWit I see you opened an Issue already (#73), that issue seems to exhibit different output and uses a different patcher.

If the issue you are having is this same issue on the Windows Patcher, please provide information on that. Otherwise this isn't the issue you want to report on, the issue you opened would be better.

**Comment by nmota21** [comment] 2021-05-06 20:47
Hey. Same issue here. Tried the fix. Came up with "no internet" warning. Checked my antivirus, and my firewall. No warnings. Disabled both. Same issues.
Changed to beta servers, and it is patching right now. Hope it helps. Using v1.4.1.3 on Windows (just reverted to 1.3.5.1 BETA)

**Comment by TheShadowEevee** [comment] 2021-05-06 21:11
I was looking at a diff between the latest stable and the beta mentioned above, and the main difference that would cause the no internet warning is the addition of [Line 3515 - Line 3528](https://github.com/RiiConnect24/RiiConnect24-Patcher/blob/master/RiiConnect24Patcher.bat#L3515); the issue is narrowing down exactly what part is triggering this issue in the curl command on Line 3517. Looking at the flags passed to curl my guess is it's something with the `--user-agent` flag, but I have no way of knowing for sure.

**Comment by TheShadowEevee** [comment] 2021-05-06 21:26
Alright, I changed some things. If anyone can test this that would be great!

I need to know what the patcher says after pressing 1 like normal; it should say `Microsoft NCSI` or `No Conn`

You can download the test patcher [here](https://raw.githubusercontent.com/TheShadowEevee/RiiConnect24-Patcher/master/RiiConnect24Patcher.bat)

If it shows a bunch of text in your web browser Right Click it and select "Save As..." and it should download like normal.

**Comment by nmota21** [comment] 2021-05-06 21:42
It snap-closes on pressing 1. Using OBS i could capture the last frame before closing. Here it is. 
![2021-05-06 22-36-48 00_00_06_24 Still001](https://user-images.githubusercontent.com/67742305/117369063-49ca2000-aebc-11eb-8d84-2bd80002838e.jpg)

**Comment by TheShadowEevee** [comment] 2021-05-06 21:45
Ah, the closing is my fault; I was running it from the command line so I forgot the window would close.

Interesting though, curl really is having issues... You do have normal connectivity right? Can you open http://www.msftncsi.com/ncsi.txt in a browser?

**Comment by nmota21** [comment] 2021-05-06 21:50
So, i tried on my computer. No joy. But, my brother's PC is on the same network. Sent him the address through Discord and it opens fine on his PC. We are both Windows 10. Does this depend on some kind of windows service that could be deactivated? i used one of those debloater tools for Win 10 recently (Privatezilla).

**Comment by TheShadowEevee** [comment] 2021-05-06 21:53
It shouldn't; it's a public website. What error did the browser give you when it couldn't connect? That might help figure out the issue.

**Comment by nmota21** [comment] 2021-05-06 21:55
Both Chrome and Brave give the regular "Site can't be reached". Chrome gives the "DNS_PROBE_FINISHED_NXDOMAIN", and Brave the "ERR_NAME_NOT_RESOLVED"

**Comment by TheShadowEevee** [comment] 2021-05-06 22:00
Odd; I'm wondering if it could potentially be a DNS issue but I don't see why that would be the case for only a few people...
That domain is normally the one Windows pings when testing if you have internet, it controls the little wifi/ethernet icon on the taskbar, so I'm not sure what could be different that's causing this issue.

More research is needed here for sure to solve this

**Comment by nmota21** [comment] 2021-05-06 22:40
My guess is that the issue is more on the user side, as my brother's pc is way more "vanilla" than mine. I already cleared the hosts file, cleared dns, and checked the services. No luck. I'll edit this message in few minutes, if choosing the BETA option works as a workaround for those with issues. Going to install it on my Wii now.

**Closed** 2022-01-08 21:41 UTC
Labels: bug, Windows
